package com.fit2081.ter_34857613.NutriTrack.model.database.Entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Entity representing tips generated by GenAI in the NutriCoach section.
 * Maps to the "nutri_coach_tips" table in the Room database.
 * Contains foreign key relationship to the Patient entity.
 */
@Entity(
    tableName = "nutri_coach_tips",
    foreignKeys = [
        ForeignKey(
            entity = Patient::class,
            parentColumns = ["userId"],
            childColumns = ["userId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("userId")]
)
data class NutriCoachTip(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val userId: String, // Foreign key to Patient
    val timestamp: Long, // When the tip was generated
    val content: String, // The actual tip content
    val category: String // Category of the tip (e.g., "Fruit", "Vegetables", "General")
) 